apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: alloy-core-akkanucleus-worker
spec:
  rules:
  - host: at4dw.liaison.dev
    http:
      paths:
      - backend:
          serviceName: alloy-core-akkanucleus-worker
          servicePort: 8989
        path: /akka-nucleus
  tls:
  - hosts:
    - at4dw.liaison.dev